#!/bin/sh

case $1 in
   config)
        cat <<'EOM'
graph_title DSL rate 
graph_vlabel bits in (-) / out (+)
graph_args --base 1000
graph_category network

down.label received
down.graph no
down.min 0
up.label bps
up.negative down
up.min 0

mdown.label max received
mdown.graph no
mdown.min 0
mup.label max bps
mup.negative mdown
mup.min 0

EOM
        exit 0;;
esac


printf "down.value "
$(dirname $0)/.get_status | grep \\.data_rate_down=| cut -d'=' -s -f2
printf "up.value "
$(dirname $0)/.get_status | grep \\.data_rate_up=| cut -d'=' -s -f2
printf "mdown.value "
$(dirname $0)/.get_status | grep \\.max_data_rate_down=| cut -d'=' -s -f2
printf "mup.value "
$(dirname $0)/.get_status | grep \\.max_data_rate_up=| cut -d'=' -s -f2
