#!/bin/sh

case $1 in
   config)
        cat <<'EOM'
graph_title DSL rate 
graph_vlabel bits in (-) / out (+)
graph_args --base 1000
graph_category network

down.label received
down.type DERIVE
down.graph no
#dowm.cdef down,8,*
down.min 0
up.label bps
up.type DERIVE
up.negative down
#up.cdef up,8,*
up.min 0

mdown.label received
mdown.type DERIVE
mdown.graph no
#mdowm.cdef down,8,*
mdown.min 0
mup.label bps
mup.type DERIVE
mup.negative down
#mup.cdef up,8,*
mup.min 0

EOM
        exit 0;;
esac


printf "down.value "
$(dirname $0)/.get_status | grep \\.data_rate_down=| cut -d'=' -s -f2
printf "up.value "
$(dirname $0)/.get_status | grep \\.data_rate_up=| cut -d'=' -s -f2
printf "mdown.value "
$(dirname $0)/.get_status | grep \\.max_data_rate_down=| cut -d'=' -s -f2
printf "mup.value "
$(dirname $0)/.get_status | grep \\.max_data_rate_up=| cut -d'=' -s -f2
