#!/bin/sh

case $1 in
   config)
        cat <<'EOM'
graph_title DSL rate 
graph_vlabel bits in (-) / out (+)
graph_args --base 1000
graph_category network

down.label received
down.type DERIVE
down.graph no
#dowm.cdef down,8,*
down.min 0
up.label bps
up.type DERIVE
up.negative down
#up.cdef up,8,*
up.min 0

EOM
        exit 0;;
esac




printf "down.value "
/etc/init.d/dsl_control lucistat | grep rate_down=| cut -d'=' -s -f2
printf "up.value "
/etc/init.d/dsl_control lucistat | grep rate_up=| cut -d'=' -s -f2
